config/routes.rb
Rails.application.routes.draw do

  get 'favorites/create'
  get 'favorites/destroy'
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :artworks
  resources :colors, only: [:create, :destroy, :show] 
  resources :users do
    member do
      get :likes
    end
  end
  
  resources :favorites, only: [:create, :destroy] 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :color
  belongs_to :user
  mount_uploader :content, ImageUploader
  validates :title, presence: true, length: { maximum: 30 }
  
  # お気に入り機能
  has_many :favorites, dependent: :destroy
  has_many :liker, through: :favorites, source: :user
  
end

app/models/color.rb
class Color < ApplicationRecord
  validates :hue, presence: true, length: { maximum: 50 }
  has_many :artworks
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :artwork
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  # お気に入り機能
  has_many :artworks
  has_many :favorites, dependent: :destroy
  has_many :fav_posts, through: :favorites, source: :artwork
  
  def like(artwork)
    favorites.find_or_create_by(artwork_id: artwork.id)
  end
  
  def unlike(artwork)
    favorite = self.favorites.find_by(artwork_id: artwork.id)
    favorite.destroy if favorite
  end
  
  def add_favorite?(artwork)
    self.fav_posts.include?(artwork)
    #has_manyで定義したfav_postにする
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]
  
  def index
    @artworks = Artwork.all
  end

  def show
  end
  
  def new
#    @artwork = Artwork.new
    @artwork = current_user.artworks.build
  end

  def edit
  end
  
  def create
    @artwork = current_user.artworks.build(artwork_params)
    if @artwork.save
      flash[:success] = '作品 が正常に投稿されました'
      redirect_to @artwork
    else
      
      flash.now[:denger] = '作品 が正常に投稿されませんでした'
      render :new
    end
  end
  
  def update
    if @artwork.save
      flash[:success] = 'Message が正常に投稿されました'
      redirect_to @artwork
    else
      flash.now[:denger] = 'Message が正常に投稿されませんでした'
      render :new
    end
  end

  def destroy
    @artwork.destroy

    flash[:success] = 'Message は正常に削除されました'
    redirect_to artworks_url
  end


  private

  def set_artwork
    @artwork = Artwork.find(params[:id])
  end
  
  # Strong Parameter
  # Never trust parameters from the scary internet, only allow the white list through.
  # color_id を追加
  def artwork_params
    params.require(:artwork).permit(:color_id, :title, :content)
  end
  
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def index
  end
  
  def show
    @color = Color.find(params[:id])
    @artworks = @color.artworks.order(id: :desc)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    artwork = Artwork.find(params[:artwork_id])
    current_user.like(artwork)
    flash[:success] = 'お気に入りに追加しました'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    artwork = Artwork.find(params[:artwork_id])
    current_user.unlike(artwork)
    flash[:success] = 'お気に入りを解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    # urlにcategory_id(params)がある場合
    if params[:color_id]
      # Categoryのデータベースのテーブルから一致するidを取得
      @color = Color.find(params[:color_id])
       
      # category_idと紐づく投稿を取得
      @artworks = @color.artworks.order(created_at: :desc).all
    else
      # 投稿すべてを取得
      @artworks = Artwork.order(created_at: :desc).all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ログインしないと………
  before_action :require_user_logged_in, only: [:show]

  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @artworks = @user.artworks.order(id: :desc).page(params[:page])
  end
  
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました'
      render :new
    end
  end
  
  def update
    @user = User.find(params[:id])
     #編集しようとしてるユーザーがログインユーザーとイコールかをチェック
    if current_user == @user
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を編集しました'
        redirect_to @user
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
      end 
    end
  end

  def destroy
    @user = User.find(params[:id])
     #編集しようとしてるユーザーがログインユーザーとイコールかをチェック
    if current_user == @user
      if @user.destroy
        flash[:success] = 'ユーザー情報を編集しました'
        redirect_to root_url
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        redirect_back(fallback_location: root_path)
      end 
    end
   end

  def likes
    @user = User.find(params[:id])
    @artworks = @user.fav_posts.page (params[:page])
  end

  private

  def set_artwork
  end
  
  
  def user_params
    params.require(:user).permit(:name, :email, :profile, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artworks/_artworks.html.erb
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artworks.each do |artwork| %>
      <tr>
        <td rowSpan=5><%= image_tag artwork.content.url if artwork.content? %></td>
      </tr>
      <tr>
        <td>Title : <%= artwork.title %> </td>
      </tr>
      <tr>
        <td> User: <%= link_to artwork.user.name, user_path(artwork.user) %></td>
      </tr>
     
      <tr>
        <td>Color : <%= artwork.color.hue %></td>
      </tr>
      
      <tr>
        <td><%= link_to 'Show', artwork, class: 'btn btn-primary btn-sm' %></td>
        <% if current_user == artwork.user %>

        <% else %>
          <% if current_user.add_favorite?(artwork) %>
              <td>
              <%= form_with(model: current_user.favorites.find_by(artwork_id: artwork.id), local: true, method: :delete) do |f| %>
              <%= hidden_field_tag :artwork_id, artwork.id %>
              <%= f.submit 'Unlike', class: 'btn btn-warning btn-sm' %>
              </td>
            <% end %>
          <% else %>
            <td>
            <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
              <%= hidden_field_tag :artwork_id, artwork.id %>
              <%= f.submit 'Like', class: 'btn btn-primary btn-sm' %>
            <% end %>
            </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/artworks/_form.html.erb
<%= form_with(model: artwork, local: true) do |form| %>
  <% if artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artwork.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= image_tag @artwork.content.url if @artwork.content? %>
    
  <%= form_for @artwork do |f| %>
  <div class="field">
    <%= f.label :color_id %>
    <%= f.collection_select :color_id, Color.all, :id, :hue, include_blank: "選択して下さい" %>
  </div>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.file_field :content %>
  </div>
    <div class="actions">
    <%= form.submit %>
  </div>
  
  <% end %>

<% end %>

app/views/artworks/destroy.html.erb
<h1>Artworks#destroy</h1>
<p>Find me in app/views/artworks/destroy.html.erb</p>

app/views/artworks/edit.html.erb
<h1>Editing artwork</h1>

<%= render 'form', artwork: @artwork %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', root_path %>

app/views/artworks/index.html.erb
<h1>Artworks</h1>

<%= render 'artworks', artwork: @artwork %>

<br>

<%= link_to 'New artwork', new_artwork_path %>

app/views/artworks/new.html.erb
<h1>New Artwork</h1>

<%= render 'form', artwork: @artwork %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<table>
  <thead>
    <strong>Image:</strong>
  </thead>
  <tbody>
    <tr><td>Title : <%= @artwork.title %></td></tr>
    <tr><td>User :  <%= link_to @artwork.user.name, user_path(@artwork.user) %></td></tr>
    <tr><td>Color : <%= @artwork.color.hue %></td></tr>  
  </tbody>
</table>

<p>
  <%= image_tag @artwork.content.url if @artwork.content? %>
</p>

<% if current_user == @artwork.user %>
        <p>
        <span><%= link_to 'Edit', edit_artwork_path(@artwork), class: 'btn btn-primary btn-sm' %></span>
        <span><%= link_to 'Destroy', @artwork, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></span>
        </p>
<% end %>
        <p><%= link_to 'Back', root_path, class: 'btn btn-primary btn-sm' %></p>

app/views/colors/_color_select.html.erb
  <ul class="nav nav-tabs nav-justified mb-3">
    <li class="nav-item"><%= link_to 'Red', :controller => 'colors', :action => 'show', id: 1 %></li>
    <li class="nav-item"><%= link_to 'Orenge', :controller => 'colors', :action => 'show', id: 2 %></li>
    <li class="nav-item"><%= link_to 'Yellow', :controller => 'colors', :action => 'show', id: 3 %></li>
    <li class="nav-item"><%= link_to 'Green', :controller => 'colors', :action => 'show', id: 4 %></li>
    <li class="nav-item"><%= link_to 'Blue', :controller => 'colors', :action => 'show', id: 5 %></li>
    <li class="nav-item"><%= link_to 'Purple', :controller => 'colors', :action => 'show', id: 6 %></li>
    <li class="nav-item"><%= link_to 'Wite', :controller => 'colors', :action => 'show', id: 7 %></li>
    <li class="nav-item"><%= link_to 'Black', :controller => 'colors', :action => 'show', id: 8 %></li>
  </ul>
</nav>

app/views/colors/show.html.erb
  <%= render 'colors/color_select' %>
  <%= render 'artworks/artworks', artwork: @artworks %>

app/views/favorites/_favorite_button.html.erb
<% unless current_user == user %>
  <% if current_user.add_favorite?(artwork) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Front Colors</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'New artwork', new_artwork_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Favorites', likes_user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Front Color</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>

  <%= render 'colors/color_select' %>

  <%= render 'artworks/artworks', artwork: @artworks %>
  
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to Front Colors</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">

        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>ユーザ情報編集</h1>
</div>


<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>

      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :profile, 'Profile' %>
        <%= f.text_field :profile, :maxlength => "255", :size => "80x5", class: 'form-control' %>
      </div>
      

    <div class="accbox">
      <label for="label1">パスワードを変更するかたはこちら</label>
      <input type="checkbox" id="label1" class="cssacc" />
      <div class="accshow">
        
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      </div>
    </div>
      <%= f.submit 'Submit', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <% if current_user == @user %>
        <p><%= link_to 'Edit', edit_user_path(current_user) %></p>
        <% end %>
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Artworks</a></li>
      <li class="nav-item"><a href="<% likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorites</a></li>
    </ul>
    <%= render 'artworks/artworks', artworks: @artworks %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <%= @user.profile %>
      <% if current_user == @user %>
        <p><%= link_to 'Edit', edit_user_path(current_user) %></p>
      <% end %>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Artworks</a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorites</a></li>
    </ul>
    
    <%= render 'artworks/artworks', artwork: @artwork %>
  </div>
</div>